### ISSUE TITLE
Errors when running sample code

### ISSUE THREAD

**Issue by tomrippetoe** [odoe/esrijs4-vm-ember#1]
Hello.

After following the README install/run directions, when i try to run the app locally (in Firefox), i get the following two errors:

Error: Assertion Failed: Ember Views equireray jQuery between 1.7 and 2.1
Error: Could not find module `ember` imported from `esrijs4-vm-ember/app`

When i try to use the Firefox Ember Addon, it tells me that the app isn't an Ember app.  And then i get a slew of 404 error messages in the Console that look something like this:

http://js.arcgis.com/4.0beta3/dojo/ember-debug/addons/ember-new-computed/utils/can-use-new-......

I am a one-day-old Ember user so i am not sure where to start debugging those errors.  Any thoughts?

Thanks,
Tom

**Comment by odoe** [comment]
Thanks!

That was weird, the jQuery issues had to with the bower version. So fixed that and updated the ember-cli version. Tested and seems to work now.

**Comment by tomrippetoe** [comment]
Thank you for the update. I too was able to get the sample running with Ember 1.13.14.   Then i got greedy. I have spent my day trying to get the app running with the Ember-cli 2.2.0 @ beta 4, with no good luck at all.

And i am still a bit befuddled on how to debug what exactly is broken.  Any thoughts on how to head down the path with esrijs api and Ember 2.2?

**Comment by tomrippetoe** [comment]
I had some minor success using your code (with a few modifications) with the Ember-cli 2.2 release.... I can get the map to appear, with the locate and home buttons. but so far, neither the locate nor the home buttons function. the code flow gets to the associated 'enabled' actions, but the calls on the viewmodel, e,g, 'goHome', do not seem to work (e.g. the map extent does not change after clicking the home button). 

So, i have several questions i'd like to throw out.  Would it be better if i opened a new issue? perhaps email you directly? ask them here?

Thanks again for your help

**Comment by tomrippetoe** [comment]
I am happy to report I have the ViewModel code working in Ember 2.2.  There seems to be a couple of issues:
1) 'view' is perhaps a reserved word now. In index.hbs i had to change all instances of 'view' to 'mapview' in the component declaration
2) Ember seems to care more about the name of properties (at least) when creating esri objects. for example, your code has (with changes mentioned in (1)):

``` javascript
let mapView = this.get('mapView');
let vm = new HomeVM({ mapView });
```

and that code didnt work for me. But when i was explicit about including the property name in the constructors, that did work. For example:

``` javascript
let mapView = this.get('mapView');
let vm = new HomeVM({ view: mapView }); 
```

Hopefully I am off and running (and can stop pestering you :)  .

Thanks.

**Comment by odoe** [comment]
That's awesome to hear! I haven't gotten around to fully testing 2.2 yet, but it looks like you're off to a great start! Thanks!

**Comment by tomrippetoe** [comment]
It’s a start for sure, but still a long way to go.

In addition to being an Ember newbie, I am also a GitHub novice. What’s the etiquette and protocol for uploading my changes back to GitHub?  Do I need to branch, create a new repository, etc? My goal is to share your code and my changes with my team so we can use it a shared starting point for our current project.

Thanks,
Tom

**Comment by odoe** [comment]
You already have a fork of the project in your github account that you can continue to update. I'm not taking PRs on this repo as of yet, since 2.2 is still a beta, but you can update your own fork as much as you like!

Thanks!
